services:
  - type: web
    name: newdayai
    env: python
    plan: free
    buildCommand: |
     pip install -r requirements.txt
     playwright install chromium
     playwright install-deps
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
